### ISSUE TITLE
关于npy数据集

### ISSUE THREAD

**Issue by rideragito** [rami0205/NGramSwin#2]
研究者您好，我想复现一下您的这个代码，但是我在将原本的png格式数据集的转换成npy格式时出了错误，可以拜托您将npy格式的数据集链接分享一下吗？感谢您！

**Comment by rami0205** [comment]
Please leave your comment using English.
Unfortunately, I do not understand Chinese.

**Comment by rideragito** [comment]
I am sorry to have caused you any problems. When I was trying to reproduce your code, I noticed that the dataset image you used was in npy format, however I only have the dataset in png format. As I am having problems trying to change the dataset format, I would like to test directly with your npy dataset. I wonder if you could share the link to the dataset or could send it to my email. With all my best wishes!
(PS: please forgive me if I have problems with the English presentation)
e-mail: ts21060210p31@cumt.edu.cn

**Comment by rami0205** [comment]
Okay, I will let you know the link soon.
I will leave it on this github issue's comment.

**Comment by rideragito** [comment]
Thank you very much for your help!

**Comment by rami0205** [comment]
testset .npy file link (due to my limited cloud storage issue, this link will be expired and the files in this link will be deleted at the end of this year.)
[https://1drv.ms/f/s!AoUesdU_BVZrivlVY04u7WHcSapUWg?e=eBBVfd](https://1drv.ms/f/s!AoUesdU_BVZrivlVY04u7WHcSapUWg?e=eBBVfd)

for producing training npy file, please run the code below with proper edits.
the data in numpy array will be saved as numpy.uint8 data structure.

```
from PIL import Image
import numpy as np

img = Image.open(PATH) # PATH: .png file
img_np = np.transpose(np.array(img), (2,0,1))
np.save('filename.npy', img_np)
```
